# Python Programming Dasar
Anda dapat mengakses website python di .[Python](http://python.org/)
<br>
Anda dapat mengunduh Anaconda di website .[Anaconda](https://www.anaconda.com/distribution/)

* * *

## 1. Business Understanding
### 1.1 Latar Belakang

* Karena **belum adanya data** mengenai *jumlah jenis mobil* di Jakarta
* Dan lain-lain
    * List yg lain

### 1.2 Tujuan

1. Untuk membuat model prediksi jenis mobi
2. Untuk meningkatkan produktivitas
3. Untuk meningkatkan pendapatan
    1. Satu
    2. Dua
    3. Tiga

### 1.3 Manfaat
1. Mengetahui model prediksi jenis mobil
2. Dapat meningkatkan produktivias

![Gambar Internet](https://imgx.gridoto.com/crop/0x0:1417x868/700x465/photo/2019/01/05/1877290494.jpg)
![Gambar Folder](Downloads/jasa-marga.jpg)

***

## 2. Data Understanding

## 3. Data Preparation

## 4. Modeling

## 5. Evaluation

## 6. Data Presentation

In [11]:
print("Hello World!")
print(2+3)

Hello World!
5

In [17]:
# Arithmatic operation
print(10+3)
print(10-3)
print(-10)
print(10*3)
print(10**3)
print(10/3)
print(10//3)
print(10%3)

13
7
-10
30
1000
3.3333333333333335
3
1

In [25]:
# List
Fam = [2,3,4,5,6,7]
print(Fam)
type(Fam)

[2, 3, 4, 5, 6, 7]

list

In [68]:
## List Inside List
Data =[["Bob",160],["Char", 150],["Brian", 140.5]]
print(Data)
print(Data[0][1])
print(Data[0][0])

animal = "CHICKEN"
print(animal[0:3])
print(animal[0:-2])

[['Bob', 160], ['Char', 150], ['Brian', 140.5]]
160
Bob
CHI
CHICK

In [41]:
# Function
## Build-In
print(Fam)
print(max(Fam))
print(min(Fam))
print(len(Fam)) #jumlah data

[2, 3, 4, 5, 6, 7]
7
2
6

In [46]:
# Function
## User Defined
print(Data)
x,y = max(Data, key=lambda a :a[1])
print(x)
print(y)

[['Bob', 160], ['Char', 150], ['Brian', 140.5]]
Bob
160

In [62]:
# Method
name = "hello world"
print(name)
print(type(name))
### "hello world" type is string
### some methods specifically
### associated with string 
print (name.capitalize())
print (name.upper())
print (name.lower())
name= "          hello world    "
print (name.strip())

b'wwwexamplecom'.strip(b'cmow')

hello world
<class 'str'>
Hello world
HELLO WORLD
hello world
hello world

b'example'

In [69]:
# Loop and Map
animals = ['cat', 'dog', 'monkey']
for animal in animals :
    print (animal)
    nums = [0, 1, 2, 3, 4]
    squares = [x ** 2 for x in nums]
print(squares)

cat
dog
monkey
[0, 1, 4, 9, 16]

In [71]:
# EXERCISE
## 1. Buat Variabel Harga, lalu isi dengan 10000
## 2. Tipe data dari variabel harga adalah
harga = 10000
print(harga)
type(harga)

10000

int

In [74]:
## 3. Buat variabel rating, lalu isi dengan 5.9
## 4. Tipe data dari variabel rating
rating = 5.9
type(rating)

float

In [79]:
## 5. nama_variabel = 'Python untuk pemula'
## 6. Tipe daa
nama_variabel = 'Python untuk pemula'
print (nama_variabel)
print(nama_variabel [0])
print(nama_variabel [-1])
print(nama_variabel [0:5])
print(nama_variabel [1:-1])

Python untuk pemula
P
a
Pytho
ython untuk pemul

In [81]:
# If Statement >> evaluation condition
a = 10
b = 20

if a==b :
    print('yes')
else :
    print('no')

no

In [87]:
# If Statement
a = 10
b = 20
c = 30

if a==b :
    print('yes')
elif a==c :
    print('yes')
else :
    print('no')

no

In [90]:
# NumPy Array >> di dalam module ada function

## Install and import
pip3 install numpy
import numpy as np

In [102]:
# NumPy Array
import numpy as np

Data =[["Bob",160],["Char", 150],["Brian", 140.5]] # list build-in
print (Data)

height_list = [row[1] for row in Data]
print (height_list)
type (height_list)

height_array = np.array(height_list)
print (height_array)
type (height_array)

[['Bob', 160], ['Char', 150], ['Brian', 140.5]]
[160, 150, 140.5]
[160.  150.  140.5]

numpy.ndarray

In [105]:
# Dictionary >>  associative array (build-in)
countries = ['spain', 'france', 'germany', 'norway']
capitals  = ['madrid', 'paris', 'berlin', 'oslo']

ind_ger = countries.index ('germany')
print (capitals[ind_ger])

berlin

In [111]:
europe = {'spain':'madrid', 'france':'paris', 'germany':'berlin', 'norway':'oslo'}
type (europe)

dict

In [113]:
print (europe)

{'spain': 'madrid', 'france': 'paris', 'germany': 'berlin', 'norway': 'oslo'}

In [115]:
print (europe.keys())

dict_keys(['spain', 'france', 'germany', 'norway'])

In [117]:
print (europe.values())

dict_values(['madrid', 'paris', 'berlin', 'oslo'])

In [119]:
print (europe['norway'])

oslo

### Pandas
untuk melakukan agregat
* high level data manipulation tool
* build on numpy
* store the tabular data in data frame

In [133]:
## Install and import
import pandas as pd

## Build dataframe from
europe = {'spain':['madrid'], 'france':['paris'], 'germany':['berlin'], 'norway':['oslo']}
pd.DataFrame (europe)

  france germany norway   spain
0  paris  berlin   oslo  madrid

In [141]:
pd.read_csv('C:/Users/afifah064126/Downloads/GroupProject--IMDB-master/GroupProject--IMDB-master/Dataset/IMDB-database.csv',
           encoding = "latin1")

,movie_ID,movie_title,duration,color,title_year,country,language,content_rating,budget_USD,gross_USD,...,actor_3_facebook?,actor_3_facebook_likes,cast_total_facebook_likes,movie_facebook?,movie_facebook_likes;,facenumber_in_poster,num_voted_users,num_user_for_reviews,imdb_score,imdb_top_250
0,1,Avatar,178,1,2009,USA,English,PG-13,237000000,760505847,...,1,855,4834,1,33000,0,886204,3054,7.9,0
1,2,Pirates of the Caribbean: At World's End,169,1,2007,USA,English,PG-13,300000000,309404152,...,1,1000,48350,0,0,0,471220,1238,7.1,0
2,3,The Dark Knight Rises,164,1,2012,USA,English,PG-13,250000000,448130642,...,1,23000,106759,1,164000,0,1144337,2701,8.5,1
3,4,Spider-Man 3,156,1,2007,USA,English,PG-13,258000000,336530303,...,1,4000,46055,0,0,0,383056,1902,6.2,0
4,5,Batman v Superman: Dawn of Justice,183,1,2016,USA,English,PG-13,250000000,330249062,...,1,2000,24450,1,197000,0,371639,3018,6.9,0
5,6,Superman Returns,169,1,2006,USA,English,PG-13,209000000,200069408,...,1,903,29991,0,0,0,240396,2367,6.1,0
6,7,Man of Steel,143,1,2013,USA,English,PG-13,225000000,291021565,...,1,748,20495,1,118000,0,548573,2536,7.2,0
7,8,The Hobbit: The Battle of the Five Armies,164,1,2014,New Zealand,English,PG-13,250000000,255108370,...,1,773,9152,1,65000,0,354228,802,7.5,0
8,9,The Amazing Spider-Man,153,1,2012,USA,English,PG-13,230000000,262030663,...,1,963,28489,1,56000,0,451803,1225,7.0,0
9,10,Robin Hood,156,1,2010,USA,English,PG-13,200000000,105219735,...,1,738,3244,1,17000,0,211765,546,6.7,0
10,11,King Kong,201,1,2005,New Zealand,English,PG-13,207000000,218051260,...,1,84,7123,0,0,0,316018,2618,7.2,0
11,12,Titanic,194,1,1997,USA,English,PG-13,200000000,658672302,...,1,794,45223,1,26000,0,793059,2528,7.7,0
12,13,Captain America: Civil War,147,1,2016,USA,English,PG-13,250000000,407197282,...,1,11000,64798,1,72000,0,272670,1022,8.2,1
13,14,Battleship,131,1,2012,USA,English,PG-13,209000000,65173160,...,1,627,26679,1,44000,0,202382,751,5.9,0
14,15,Jurassic World,124,1,2015,USA,English,PG-13,150000000,652177271,...,1,1000,8458,1,150000,0,418214,1290,7.0,0
15,16,Skyfall,143,1,2012,UK,English,PG-13,200000000,304360277,...,1,393,2039,1,80000,0,522030,1498,7.8,0
16,17,Alice in Wonderland,108,1,2010,USA,English,PG,200000000,334185206,...,1,11000,79957,1,24000,0,306320,736,6.5,0
17,18,X-Men: The Last Stand,104,1,2006,Canada,English,PG-13,210000000,234360014,...,1,560,21714,0,0,0,383427,1912,6.8,0
18,19,Monsters University,104,1,2013,USA,English,G,200000000,268488329,...,1,760,14863,1,44000,0,235025,265,7.3,0
19,20,Transformers: Revenge of the Fallen,150,1,2009,USA,English,PG-13,200000000,402076689,...,1,464,3218,0,0,0,323207,1439,6.0,0
20,21,The Amazing Spider-Man 2,142,1,2014,USA,English,PG-13,200000000,202853933,...,1,825,28631,1,41000,0,321227,1067,6.7,0
21,22,TRON: Legacy,125,1,2010,USA,English,PG,170000000,172051787,...,1,1000,25550,1,30000,0,264183,665,6.8,0
22,23,Cars 2,106,1,2011,USA,English,G,200000000,191450875,...,1,776,4482,1,10000,0,101178,283,6.3,0
23,24,Terminator Salvation,118,1,2009,USA,English,PG-13,200000000,125320003,...,1,988,27468,0,0,0,286095,974,6.6,0
24,25,Furious 7,140,1,2015,USA,English,PG-13,190000000,350034110,...,1,14000,79150,1,94000,0,278232,657,7.2,0
25,26,World War Z,123,1,2013,USA,English,PG-13,190000000,202351611,...,1,1000,32392,1,129000,0,465019,995,7.0,0
26,27,Star Trek Into Darkness,132,1,2013,USA,English,PG-13,190000000,228756232,...,1,928,21411,1,92000,0,395573,1171,7.8,0
27,28,Pacific Rim,131,1,2013,USA,English,PG-13,190000000,101785482,...,1,919,19166,1,83000,0,381148,1106,7.0,0
28,29,Brave,93,1,2012,USA,English,PG,185000000,237282182,...,1,838,5005,1,39000,0,273556,428,7.2,0
29,30,WALL-E,98,1,2008,USA,English,G,180000000,223806889,...,1,522,2975,1,16000,0,718837,1043,8.4,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3751,3752,Soul Plane,92,1,2004,USA,English,R,16000000,13922211,...,1,618,3935,0,0,9,18271,150,4.4,0
3752,3753,This Christmas,117,1,2007,USA,English,PG-13,13000000,49121934,...,1,912,6554,0,0,9,6528,32,6.1,0
3753,3754,5 Days of War,113,1,2011,Georgia,English,R,20000000,17149,...,1,18,708,0,0,9,12128,61,5.6,0
3754,3755,Sleepover,89,1,2004,USA,English,PG,10000000,8070311,...,1,2000,13626,0,0,9,12706,75,5.3,0
3755,3756,Baggage Claim,96,1,2013,USA,English,PG-13,8500000,21564616,...,1,1000,8097,0,0,9,7098,41,5.0,0
3756,3757,Best in Show,90,1,2000,USA,English,PG-13,6000000,18621249,...,1,658,4611,0,0,9,45859,340,7.5,0
3757,3758,The Players Club,104,1,1998,USA,English,R,4500000,23031390,...,1,498,2868,1,575,9,4345,26,5.6,0
3758,3759,Little Fockers,98,1,2010,USA,English,PG-13,100000000,148383780,...,1,708,24082,0,0,10,85531,152,5.5,0
3759,3760,Delivery Man,105,1,2013,USA,English,PG-13,26000000,30659817,...,1,110,1006,0,0,10,59805,95,6.4,0
3760,3761,My Big Fat Greek Wedding 2,94,1,2016,USA,English,PG-13,18000000,59573085,...,1,261,2259,1,19000,10,13562,103,6.1,0
3761,3762,Top Five,102,1,2014,USA,English,R,12000000,25277561,...,1,555,5592,0,0,10,21672,93,6.5,0
3762,3763,Movie 43,94,1,2013,USA,English,R,6000000,8828771,...,1,3000,41059,1,25000,10,79146,352,4.3,0
3763,3764,Get on the Bus,120,1,1996,USA,English,R,2400000,5731103,...,1,702,5963,1,352,10,4100,35,6.8,0
3764,3765,The Longest Yard,113,1,2005,USA,English,PG-13,82000000,158115031,...,1,421,13693,0,0,11,130070,316,6.4,0
3765,3766,I Heart Huckabees,107,1,2004,USA,English,R,22000000,12784713,...,1,678,8094,0,0,11,56813,381,6.7,0
3766,3767,Epic Movie,93,1,2007,USA,English,PG-13,20000000,39737645,...,1,729,4293,0,0,11,89687,666,2.3,0
3767,3768,One Direction: This Is Us,106,1,2013,USA,English,PG,10000000,28873374,...,1,547,2787,0,0,11,22161,68,4.1,0
3768,3769,God's Not Dead 2,120,1,2016,USA,English,PG,5000000,20773070,...,1,295,1810,0,0,11,4501,102,3.4,0
3769,3770,Valentine's Day,125,1,2010,USA,English,PG-13,52000000,110476776,...,1,11000,45696,1,9000,12,95437,211,5.7,0
3770,3771,What to Expect When You're Expecting,110,1,2012,USA,English,PG-13,40000000,41102171,...,1,651,13396,1,14000,12,57266,89,5.7,0
3771,3772,Taking Woodstock,120,1,2009,USA,English,R,30000000,7443007,...,1,210,1500,0,0,12,24663,71,6.7,0
3772,3773,Love the Coopers,107,1,2015,USA,English,PG-13,17000000,26284475,...,1,85,10691,0,0,13,9051,68,5.7,0
3773,3774,A Bridge Too Far,175,0,1977,USA,English,PG,26000000,50800000,...,1,14,669,0,0,14,40277,210,7.4,0
3774,3775,The Expendables 3,131,1,2014,USA,English,PG-13,90000000,39292022,...,1,11000,52610,1,56000,15,127258,351,6.1,0
3775,3776,Cheaper by the Dozen,94,1,2003,USA,English,PG,40000000,138614544,...,1,597,7014,0,0,15,75152,288,5.8,0
3776,3777,New Year's Eve,113,1,2011,USA,English,PG-13,56000000,54540525,...,1,307,23456,1,20000,15,66579,134,5.7,0
3777,3778,Boogie Nights,155,1,1997,USA,English,R,15000000,26384919,...,1,170,3677,0,0,15,189032,560,7.9,0
3778,3779,Battle of the Year,110,1,2013,USA,English,PG-13,20000000,8888355,...,1,826,3177,0,0,19,7894,25,5.0,0
3779,3780,The Master,144,1,2012,USA,English,R,32000000,16377274,...,1,15,427,1,27000,31,105144,405,7.1,0
3780,3781,500 Days of Summer,95,1,2009,USA,English,PG-13,7500000,32391374,...,1,11000,54075,1,40000,43,376600,494,7.7,0

In [148]:
pd.read_csv ('https://raw.githubusercontent.com/scalabretta/GroupProject--IMDB/master/Dataset/IMDB-database.csv',
            encoding = 'latin1')

,movie_ID,movie_title,duration,color,title_year,country,language,content_rating,budget_USD,gross_USD,...,actor_3_facebook?,actor_3_facebook_likes,cast_total_facebook_likes,movie_facebook?,movie_facebook_likes;,facenumber_in_poster,num_voted_users,num_user_for_reviews,imdb_score,imdb_top_250
0,1,Avatar,178,1,2009,USA,English,PG-13,237000000,760505847,...,1,855,4834,1,33000,0,886204,3054,7.9,0
1,2,Pirates of the Caribbean: At World's End,169,1,2007,USA,English,PG-13,300000000,309404152,...,1,1000,48350,0,0,0,471220,1238,7.1,0
2,3,The Dark Knight Rises,164,1,2012,USA,English,PG-13,250000000,448130642,...,1,23000,106759,1,164000,0,1144337,2701,8.5,1
3,4,Spider-Man 3,156,1,2007,USA,English,PG-13,258000000,336530303,...,1,4000,46055,0,0,0,383056,1902,6.2,0
4,5,Batman v Superman: Dawn of Justice,183,1,2016,USA,English,PG-13,250000000,330249062,...,1,2000,24450,1,197000,0,371639,3018,6.9,0
5,6,Superman Returns,169,1,2006,USA,English,PG-13,209000000,200069408,...,1,903,29991,0,0,0,240396,2367,6.1,0
6,7,Man of Steel,143,1,2013,USA,English,PG-13,225000000,291021565,...,1,748,20495,1,118000,0,548573,2536,7.2,0
7,8,The Hobbit: The Battle of the Five Armies,164,1,2014,New Zealand,English,PG-13,250000000,255108370,...,1,773,9152,1,65000,0,354228,802,7.5,0
8,9,The Amazing Spider-Man,153,1,2012,USA,English,PG-13,230000000,262030663,...,1,963,28489,1,56000,0,451803,1225,7.0,0
9,10,Robin Hood,156,1,2010,USA,English,PG-13,200000000,105219735,...,1,738,3244,1,17000,0,211765,546,6.7,0
10,11,King Kong,201,1,2005,New Zealand,English,PG-13,207000000,218051260,...,1,84,7123,0,0,0,316018,2618,7.2,0
11,12,Titanic,194,1,1997,USA,English,PG-13,200000000,658672302,...,1,794,45223,1,26000,0,793059,2528,7.7,0
12,13,Captain America: Civil War,147,1,2016,USA,English,PG-13,250000000,407197282,...,1,11000,64798,1,72000,0,272670,1022,8.2,1
13,14,Battleship,131,1,2012,USA,English,PG-13,209000000,65173160,...,1,627,26679,1,44000,0,202382,751,5.9,0
14,15,Jurassic World,124,1,2015,USA,English,PG-13,150000000,652177271,...,1,1000,8458,1,150000,0,418214,1290,7.0,0
15,16,Skyfall,143,1,2012,UK,English,PG-13,200000000,304360277,...,1,393,2039,1,80000,0,522030,1498,7.8,0
16,17,Alice in Wonderland,108,1,2010,USA,English,PG,200000000,334185206,...,1,11000,79957,1,24000,0,306320,736,6.5,0
17,18,X-Men: The Last Stand,104,1,2006,Canada,English,PG-13,210000000,234360014,...,1,560,21714,0,0,0,383427,1912,6.8,0
18,19,Monsters University,104,1,2013,USA,English,G,200000000,268488329,...,1,760,14863,1,44000,0,235025,265,7.3,0
19,20,Transformers: Revenge of the Fallen,150,1,2009,USA,English,PG-13,200000000,402076689,...,1,464,3218,0,0,0,323207,1439,6.0,0
20,21,The Amazing Spider-Man 2,142,1,2014,USA,English,PG-13,200000000,202853933,...,1,825,28631,1,41000,0,321227,1067,6.7,0
21,22,TRON: Legacy,125,1,2010,USA,English,PG,170000000,172051787,...,1,1000,25550,1,30000,0,264183,665,6.8,0
22,23,Cars 2,106,1,2011,USA,English,G,200000000,191450875,...,1,776,4482,1,10000,0,101178,283,6.3,0
23,24,Terminator Salvation,118,1,2009,USA,English,PG-13,200000000,125320003,...,1,988,27468,0,0,0,286095,974,6.6,0
24,25,Furious 7,140,1,2015,USA,English,PG-13,190000000,350034110,...,1,14000,79150,1,94000,0,278232,657,7.2,0
25,26,World War Z,123,1,2013,USA,English,PG-13,190000000,202351611,...,1,1000,32392,1,129000,0,465019,995,7.0,0
26,27,Star Trek Into Darkness,132,1,2013,USA,English,PG-13,190000000,228756232,...,1,928,21411,1,92000,0,395573,1171,7.8,0
27,28,Pacific Rim,131,1,2013,USA,English,PG-13,190000000,101785482,...,1,919,19166,1,83000,0,381148,1106,7.0,0
28,29,Brave,93,1,2012,USA,English,PG,185000000,237282182,...,1,838,5005,1,39000,0,273556,428,7.2,0
29,30,WALL-E,98,1,2008,USA,English,G,180000000,223806889,...,1,522,2975,1,16000,0,718837,1043,8.4,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3751,3752,Soul Plane,92,1,2004,USA,English,R,16000000,13922211,...,1,618,3935,0,0,9,18271,150,4.4,0
3752,3753,This Christmas,117,1,2007,USA,English,PG-13,13000000,49121934,...,1,912,6554,0,0,9,6528,32,6.1,0
3753,3754,5 Days of War,113,1,2011,Georgia,English,R,20000000,17149,...,1,18,708,0,0,9,12128,61,5.6,0
3754,3755,Sleepover,89,1,2004,USA,English,PG,10000000,8070311,...,1,2000,13626,0,0,9,12706,75,5.3,0
3755,3756,Baggage Claim,96,1,2013,USA,English,PG-13,8500000,21564616,...,1,1000,8097,0,0,9,7098,41,5.0,0
3756,3757,Best in Show,90,1,2000,USA,English,PG-13,6000000,18621249,...,1,658,4611,0,0,9,45859,340,7.5,0
3757,3758,The Players Club,104,1,1998,USA,English,R,4500000,23031390,...,1,498,2868,1,575,9,4345,26,5.6,0
3758,3759,Little Fockers,98,1,2010,USA,English,PG-13,100000000,148383780,...,1,708,24082,0,0,10,85531,152,5.5,0
3759,3760,Delivery Man,105,1,2013,USA,English,PG-13,26000000,30659817,...,1,110,1006,0,0,10,59805,95,6.4,0
3760,3761,My Big Fat Greek Wedding 2,94,1,2016,USA,English,PG-13,18000000,59573085,...,1,261,2259,1,19000,10,13562,103,6.1,0
3761,3762,Top Five,102,1,2014,USA,English,R,12000000,25277561,...,1,555,5592,0,0,10,21672,93,6.5,0
3762,3763,Movie 43,94,1,2013,USA,English,R,6000000,8828771,...,1,3000,41059,1,25000,10,79146,352,4.3,0
3763,3764,Get on the Bus,120,1,1996,USA,English,R,2400000,5731103,...,1,702,5963,1,352,10,4100,35,6.8,0
3764,3765,The Longest Yard,113,1,2005,USA,English,PG-13,82000000,158115031,...,1,421,13693,0,0,11,130070,316,6.4,0
3765,3766,I Heart Huckabees,107,1,2004,USA,English,R,22000000,12784713,...,1,678,8094,0,0,11,56813,381,6.7,0
3766,3767,Epic Movie,93,1,2007,USA,English,PG-13,20000000,39737645,...,1,729,4293,0,0,11,89687,666,2.3,0
3767,3768,One Direction: This Is Us,106,1,2013,USA,English,PG,10000000,28873374,...,1,547,2787,0,0,11,22161,68,4.1,0
3768,3769,God's Not Dead 2,120,1,2016,USA,English,PG,5000000,20773070,...,1,295,1810,0,0,11,4501,102,3.4,0
3769,3770,Valentine's Day,125,1,2010,USA,English,PG-13,52000000,110476776,...,1,11000,45696,1,9000,12,95437,211,5.7,0
3770,3771,What to Expect When You're Expecting,110,1,2012,USA,English,PG-13,40000000,41102171,...,1,651,13396,1,14000,12,57266,89,5.7,0
3771,3772,Taking Woodstock,120,1,2009,USA,English,R,30000000,7443007,...,1,210,1500,0,0,12,24663,71,6.7,0
3772,3773,Love the Coopers,107,1,2015,USA,English,PG-13,17000000,26284475,...,1,85,10691,0,0,13,9051,68,5.7,0
3773,3774,A Bridge Too Far,175,0,1977,USA,English,PG,26000000,50800000,...,1,14,669,0,0,14,40277,210,7.4,0
3774,3775,The Expendables 3,131,1,2014,USA,English,PG-13,90000000,39292022,...,1,11000,52610,1,56000,15,127258,351,6.1,0
3775,3776,Cheaper by the Dozen,94,1,2003,USA,English,PG,40000000,138614544,...,1,597,7014,0,0,15,75152,288,5.8,0
3776,3777,New Year's Eve,113,1,2011,USA,English,PG-13,56000000,54540525,...,1,307,23456,1,20000,15,66579,134,5.7,0
3777,3778,Boogie Nights,155,1,1997,USA,English,R,15000000,26384919,...,1,170,3677,0,0,15,189032,560,7.9,0
3778,3779,Battle of the Year,110,1,2013,USA,English,PG-13,20000000,8888355,...,1,826,3177,0,0,19,7894,25,5.0,0
3779,3780,The Master,144,1,2012,USA,English,R,32000000,16377274,...,1,15,427,1,27000,31,105144,405,7.1,0
3780,3781,500 Days of Summer,95,1,2009,USA,English,PG-13,7500000,32391374,...,1,11000,54075,1,40000,43,376600,494,7.7,0

In [157]:
Data_IMBD = pd.read_csv ('https://raw.githubusercontent.com/scalabretta/GroupProject--IMDB/master/Dataset/IMDB-database.csv',
                         encoding = 'latin1')
# Dimension 
Data_IMDB.shape

(3781, 32)

In [159]:
print (Data_IMDB.columns)

Index(['movie_ID', 'movie_title', 'duration', 'color', 'title_year', 'country',
       'language', 'content_rating', 'budget_USD', 'gross_USD', 'net_USD',
       'profitable', 'director_name', 'director_facebook?',
       'director_facebook_likes', 'actor_1_name', 'actor_1_facebook?',
       'actor_1_facebook_likes', 'actor_2_name', 'actor_2_facebook?',
       'actor_2_facebook_likes', 'actor_3_name', 'actor_3_facebook?',
       'actor_3_facebook_likes', 'cast_total_facebook_likes',
       'movie_facebook?', 'movie_facebook_likes;', 'facenumber_in_poster',
       'num_voted_users', 'num_user_for_reviews', 'imdb_score',
       'imdb_top_250'],
      dtype='object')

In [161]:
print (len(Data_IMDB))

3781

In [164]:
# Brief View
Data_IMDB.head(3)

,movie_ID,movie_title,duration,color,title_year,country,language,content_rating,budget_USD,gross_USD,...,actor_3_facebook?,actor_3_facebook_likes,cast_total_facebook_likes,movie_facebook?,movie_facebook_likes;,facenumber_in_poster,num_voted_users,num_user_for_reviews,imdb_score,imdb_top_250
0,1,Avatar,178,1,2009,USA,English,PG-13,237000000,760505847,...,1,855,4834,1,33000,0,886204,3054,7.9,0
1,2,Pirates of the Caribbean: At World's End,169,1,2007,USA,English,PG-13,300000000,309404152,...,1,1000,48350,0,0,0,471220,1238,7.1,0
2,3,The Dark Knight Rises,164,1,2012,USA,English,PG-13,250000000,448130642,...,1,23000,106759,1,164000,0,1144337,2701,8.5,1

In [166]:
# Brief View
Data_IMDB.tail(3)

,movie_ID,movie_title,duration,color,title_year,country,language,content_rating,budget_USD,gross_USD,...,actor_3_facebook?,actor_3_facebook_likes,cast_total_facebook_likes,movie_facebook?,movie_facebook_likes;,facenumber_in_poster,num_voted_users,num_user_for_reviews,imdb_score,imdb_top_250
3778,3779,Battle of the Year,110,1,2013,USA,English,PG-13,20000000,8888355,...,1,826,3177,0,0,19,7894,25,5.0,0
3779,3780,The Master,144,1,2012,USA,English,R,32000000,16377274,...,1,15,427,1,27000,31,105144,405,7.1,0
3780,3781,500 Days of Summer,95,1,2009,USA,English,PG-13,7500000,32391374,...,1,11000,54075,1,40000,43,376600,494,7.7,0

In [168]:
# Data Type
Data_IMDB.dtypes

movie_ID                       int64
movie_title                   object
duration                       int64
color                          int64
title_year                     int64
country                       object
language                      object
content_rating                object
budget_USD                     int64
gross_USD                      int64
net_USD                        int64
profitable                     int64
director_name                 object
director_facebook?             int64
director_facebook_likes        int64
actor_1_name                  object
actor_1_facebook?              int64
actor_1_facebook_likes         int64
actor_2_name                  object
actor_2_facebook?              int64
actor_2_facebook_likes         int64
actor_3_name                  object
actor_3_facebook?              int64
actor_3_facebook_likes         int64
cast_total_facebook_likes      int64
movie_facebook?                int64
movie_facebook_likes;          int64
facenumber_in_poster           int64
num_voted_users                int64
num_user_for_reviews           int64
imdb_score                   float64
imdb_top_250                   int64
dtype: object

In [170]:
# Data Type
Data_IMDB.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3781 entries, 0 to 3780
Data columns (total 32 columns):
movie_ID                     3781 non-null int64
movie_title                  3781 non-null object
duration                     3781 non-null int64
color                        3781 non-null int64
title_year                   3781 non-null int64
country                      3781 non-null object
language                     3781 non-null object
content_rating               3781 non-null object
budget_USD                   3781 non-null int64
gross_USD                    3781 non-null int64
net_USD                      3781 non-null int64
profitable                   3781 non-null int64
director_name                3781 non-null object
director_facebook?           3781 non-null int64
director_facebook_likes      3781 non-null int64
actor_1_name                 3781 non-null object
actor_1_facebook?            3781 non-null int64
actor_1_facebook_likes       3781 non-null int64
actor_2_name                 3781 non-null object
actor_2_facebook?            3781 non-null int64
actor_2_facebook_likes       3781 non-null int64
actor_3_name                 3781 non-null object
actor_3_facebook?            3781 non-null int64
actor_3_facebook_likes       3781 non-null int64
cast_total_facebook_likes    3781 non-null int64
movie_facebook?              3781 non-null int64
movie_facebook_likes;        3781 non-null int64
facenumber_in_poster         3781 non-null int64
num_voted_users              3781 non-null int64
num_user_for_reviews         3781 non-null int64
imdb_score                   3781 non-null float64
imdb_top_250                 3781 non-null int64
dtypes: float64(1), int64(23), object(8)
memory usage: 945.3+ KB

In [173]:
# Set DF Column Index
Data_IMDB_id = Data_IMDB.set_index("movie_ID")
print (Data_IMDB_id.shape)
Data_IMDB_id

(3781, 31)

,movie_title,duration,color,title_year,country,language,content_rating,budget_USD,gross_USD,net_USD,...,actor_3_facebook?,actor_3_facebook_likes,cast_total_facebook_likes,movie_facebook?,movie_facebook_likes;,facenumber_in_poster,num_voted_users,num_user_for_reviews,imdb_score,imdb_top_250
movie_ID,,,,,,,,,,,,,,,,,,,,,
1,Avatar,178,1,2009,USA,English,PG-13,237000000,760505847,523505847,...,1,855,4834,1,33000,0,886204,3054,7.9,0
2,Pirates of the Caribbean: At World's End,169,1,2007,USA,English,PG-13,300000000,309404152,9404152,...,1,1000,48350,0,0,0,471220,1238,7.1,0
3,The Dark Knight Rises,164,1,2012,USA,English,PG-13,250000000,448130642,198130642,...,1,23000,106759,1,164000,0,1144337,2701,8.5,1
4,Spider-Man 3,156,1,2007,USA,English,PG-13,258000000,336530303,78530303,...,1,4000,46055,0,0,0,383056,1902,6.2,0
5,Batman v Superman: Dawn of Justice,183,1,2016,USA,English,PG-13,250000000,330249062,80249062,...,1,2000,24450,1,197000,0,371639,3018,6.9,0
6,Superman Returns,169,1,2006,USA,English,PG-13,209000000,200069408,-8930592,...,1,903,29991,0,0,0,240396,2367,6.1,0
7,Man of Steel,143,1,2013,USA,English,PG-13,225000000,291021565,66021565,...,1,748,20495,1,118000,0,548573,2536,7.2,0
8,The Hobbit: The Battle of the Five Armies,164,1,2014,New Zealand,English,PG-13,250000000,255108370,5108370,...,1,773,9152,1,65000,0,354228,802,7.5,0
9,The Amazing Spider-Man,153,1,2012,USA,English,PG-13,230000000,262030663,32030663,...,1,963,28489,1,56000,0,451803,1225,7.0,0
10,Robin Hood,156,1,2010,USA,English,PG-13,200000000,105219735,-94780265,...,1,738,3244,1,17000,0,211765,546,6.7,0
11,King Kong,201,1,2005,New Zealand,English,PG-13,207000000,218051260,11051260,...,1,84,7123,0,0,0,316018,2618,7.2,0
12,Titanic,194,1,1997,USA,English,PG-13,200000000,658672302,458672302,...,1,794,45223,1,26000,0,793059,2528,7.7,0
13,Captain America: Civil War,147,1,2016,USA,English,PG-13,250000000,407197282,157197282,...,1,11000,64798,1,72000,0,272670,1022,8.2,1
14,Battleship,131,1,2012,USA,English,PG-13,209000000,65173160,-143826840,...,1,627,26679,1,44000,0,202382,751,5.9,0
15,Jurassic World,124,1,2015,USA,English,PG-13,150000000,652177271,502177271,...,1,1000,8458,1,150000,0,418214,1290,7.0,0
16,Skyfall,143,1,2012,UK,English,PG-13,200000000,304360277,104360277,...,1,393,2039,1,80000,0,522030,1498,7.8,0
17,Alice in Wonderland,108,1,2010,USA,English,PG,200000000,334185206,134185206,...,1,11000,79957,1,24000,0,306320,736,6.5,0
18,X-Men: The Last Stand,104,1,2006,Canada,English,PG-13,210000000,234360014,24360014,...,1,560,21714,0,0,0,383427,1912,6.8,0
19,Monsters University,104,1,2013,USA,English,G,200000000,268488329,68488329,...,1,760,14863,1,44000,0,235025,265,7.3,0
20,Transformers: Revenge of the Fallen,150,1,2009,USA,English,PG-13,200000000,402076689,202076689,...,1,464,3218,0,0,0,323207,1439,6.0,0
21,The Amazing Spider-Man 2,142,1,2014,USA,English,PG-13,200000000,202853933,2853933,...,1,825,28631,1,41000,0,321227,1067,6.7,0
22,TRON: Legacy,125,1,2010,USA,English,PG,170000000,172051787,2051787,...,1,1000,25550,1,30000,0,264183,665,6.8,0
23,Cars 2,106,1,2011,USA,English,G,200000000,191450875,-8549125,...,1,776,4482,1,10000,0,101178,283,6.3,0
24,Terminator Salvation,118,1,2009,USA,English,PG-13,200000000,125320003,-74679997,...,1,988,27468,0,0,0,286095,974,6.6,0
25,Furious 7,140,1,2015,USA,English,PG-13,190000000,350034110,160034110,...,1,14000,79150,1,94000,0,278232,657,7.2,0
26,World War Z,123,1,2013,USA,English,PG-13,190000000,202351611,12351611,...,1,1000,32392,1,129000,0,465019,995,7.0,0
27,Star Trek Into Darkness,132,1,2013,USA,English,PG-13,190000000,228756232,38756232,...,1,928,21411,1,92000,0,395573,1171,7.8,0
28,Pacific Rim,131,1,2013,USA,English,PG-13,190000000,101785482,-88214518,...,1,919,19166,1,83000,0,381148,1106,7.0,0
29,Brave,93,1,2012,USA,English,PG,185000000,237282182,52282182,...,1,838,5005,1,39000,0,273556,428,7.2,0
30,WALL-E,98,1,2008,USA,English,G,180000000,223806889,43806889,...,1,522,2975,1,16000,0,718837,1043,8.4,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3752,Soul Plane,92,1,2004,USA,English,R,16000000,13922211,-2077789,...,1,618,3935,0,0,9,18271,150,4.4,0
3753,This Christmas,117,1,2007,USA,English,PG-13,13000000,49121934,36121934,...,1,912,6554,0,0,9,6528,32,6.1,0
3754,5 Days of War,113,1,2011,Georgia,English,R,20000000,17149,-19982851,...,1,18,708,0,0,9,12128,61,5.6,0
3755,Sleepover,89,1,2004,USA,English,PG,10000000,8070311,-1929689,...,1,2000,13626,0,0,9,12706,75,5.3,0
3756,Baggage Claim,96,1,2013,USA,English,PG-13,8500000,21564616,13064616,...,1,1000,8097,0,0,9,7098,41,5.0,0
3757,Best in Show,90,1,2000,USA,English,PG-13,6000000,18621249,12621249,...,1,658,4611,0,0,9,45859,340,7.5,0
3758,The Players Club,104,1,1998,USA,English,R,4500000,23031390,18531390,...,1,498,2868,1,575,9,4345,26,5.6,0
3759,Little Fockers,98,1,2010,USA,English,PG-13,100000000,148383780,48383780,...,1,708,24082,0,0,10,85531,152,5.5,0
3760,Delivery Man,105,1,2013,USA,English,PG-13,26000000,30659817,4659817,...,1,110,1006,0,0,10,59805,95,6.4,0
3761,My Big Fat Greek Wedding 2,94,1,2016,USA,English,PG-13,18000000,59573085,41573085,...,1,261,2259,1,19000,10,13562,103,6.1,0
3762,Top Five,102,1,2014,USA,English,R,12000000,25277561,13277561,...,1,555,5592,0,0,10,21672,93,6.5,0
3763,Movie 43,94,1,2013,USA,English,R,6000000,8828771,2828771,...,1,3000,41059,1,25000,10,79146,352,4.3,0
3764,Get on the Bus,120,1,1996,USA,English,R,2400000,5731103,3331103,...,1,702,5963,1,352,10,4100,35,6.8,0
3765,The Longest Yard,113,1,2005,USA,English,PG-13,82000000,158115031,76115031,...,1,421,13693,0,0,11,130070,316,6.4,0
3766,I Heart Huckabees,107,1,2004,USA,English,R,22000000,12784713,-9215287,...,1,678,8094,0,0,11,56813,381,6.7,0
3767,Epic Movie,93,1,2007,USA,English,PG-13,20000000,39737645,19737645,...,1,729,4293,0,0,11,89687,666,2.3,0
3768,One Direction: This Is Us,106,1,2013,USA,English,PG,10000000,28873374,18873374,...,1,547,2787,0,0,11,22161,68,4.1,0
3769,God's Not Dead 2,120,1,2016,USA,English,PG,5000000,20773070,15773070,...,1,295,1810,0,0,11,4501,102,3.4,0
3770,Valentine's Day,125,1,2010,USA,English,PG-13,52000000,110476776,58476776,...,1,11000,45696,1,9000,12,95437,211,5.7,0
3771,What to Expect When You're Expecting,110,1,2012,USA,English,PG-13,40000000,41102171,1102171,...,1,651,13396,1,14000,12,57266,89,5.7,0
3772,Taking Woodstock,120,1,2009,USA,English,R,30000000,7443007,-22556993,...,1,210,1500,0,0,12,24663,71,6.7,0
3773,Love the Coopers,107,1,2015,USA,English,PG-13,17000000,26284475,9284475,...,1,85,10691,0,0,13,9051,68,5.7,0
3774,A Bridge Too Far,175,0,1977,USA,English,PG,26000000,50800000,24800000,...,1,14,669,0,0,14,40277,210,7.4,0
3775,The Expendables 3,131,1,2014,USA,English,PG-13,90000000,39292022,-50707978,...,1,11000,52610,1,56000,15,127258,351,6.1,0
3776,Cheaper by the Dozen,94,1,2003,USA,English,PG,40000000,138614544,98614544,...,1,597,7014,0,0,15,75152,288,5.8,0
3777,New Year's Eve,113,1,2011,USA,English,PG-13,56000000,54540525,-1459475,...,1,307,23456,1,20000,15,66579,134,5.7,0
3778,Boogie Nights,155,1,1997,USA,English,R,15000000,26384919,11384919,...,1,170,3677,0,0,15,189032,560,7.9,0
3779,Battle of the Year,110,1,2013,USA,English,PG-13,20000000,8888355,-11111645,...,1,826,3177,0,0,19,7894,25,5.0,0
3780,The Master,144,1,2012,USA,English,R,32000000,16377274,-15622726,...,1,15,427,1,27000,31,105144,405,7.1,0
3781,500 Days of Summer,95,1,2009,USA,English,PG-13,7500000,32391374,24891374,...,1,11000,54075,1,40000,43,376600,494,7.7,0

#### Convert Dict to DataFrame

In [212]:
code  = ['US', 'AUS', 'JPN', 'IN', 'RUS', 'MOR', 'EG']
names = ['United States', 'Australia', 'Japan', 'India','Russia','Morocco', 'Egypt']
dr    = [True, False, False, False, True, True, True]
cpc   = [809, 731, 588, 18, 200, 70, 45]
         
# Create dictionary my_dict with three key:value pairs: my_dict
my_dict = {'ctrcode':code, 'country':names, 'drives_right':dr,'cars_per_cap':cpc}
cars = pd.DataFrame(my_dict)

print(type(cars))
print(cars)

<class 'pandas.core.frame.DataFrame'>
   cars_per_cap        country ctrcode  drives_right
0           809  United States      US          True
1           731      Australia     AUS         False
2           588          Japan     JPN         False
3            18          India      IN         False
4           200         Russia     RUS          True
5            70        Morocco     MOR          True
6            45          Egypt      EG          True

#### Pandas loc and iloc

In [203]:
cars_id = cars.set_index("ctrcode") 
print(cars_id.shape) 
cars_id

(7, 3)

         cars_per_cap        country  drives_right
ctrcode
US                809  United States          True
AUS               731      Australia         False
JPN               588          Japan         False
IN                 18          India         False
RUS               200         Russia          True
MOR                70        Morocco          True
EG                 45          Egypt          True

In [204]:
cars_id['country'], cars_id[['country']] 
cars_id[0:3]

         cars_per_cap        country  drives_right
ctrcode
US                809  United States          True
AUS               731      Australia         False
JPN               588          Japan         False

In [208]:
# row & column access
cars_id.loc[['AUS', 'EG']]

         cars_per_cap    country  drives_right
ctrcode
AUS               731  Australia         False
EG                 45      Egypt          True

In [209]:
 # row access
cars_id.loc[['RUS', 'MOR'], ['country', 'drives_right']]

         country  drives_right
ctrcode
RUS       Russia          True
MOR      Morocco          True

#### Where Clause and Sort
* filtering with columns rather than index
* similar WHERE in SQL

In [214]:
import pandas as pd
print(cars_id[cars_id.drives_right == True]) 
print(cars_id[(cars_id.cars_per_cap > 100) & (Data_IMDB_id.country == "Australia") ])

         cars_per_cap        country  drives_right
ctrcode
US                809  United States          True
RUS               200         Russia          True
MOR                70        Morocco          True
EG                 45          Egypt          True
Empty DataFrame
Columns: [cars_per_cap, country, drives_right]
Index: []

C:\Users\afifah064126\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\indexes\base.py:3140: RuntimeWarning: '<' not supported between instances of 'str' and 'int', sort order is undefined for incomparable objects
  return this.join(other, how=how, return_indexers=return_indexers)
C:\Users\afifah064126\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:3: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  This is separate from the ipykernel package so we can avoid doing imports until

In [217]:
cars_id.sort_values(by=['cars_per_cap'])

         cars_per_cap        country  drives_right
ctrcode
IN                 18          India         False
EG                 45          Egypt          True
MOR                70        Morocco          True
RUS               200         Russia          True
JPN               588          Japan         False
AUS               731      Australia         False
US                809  United States          True

In [219]:
cars_id.sort_values(by=['cars_per_cap'], ascending=False)

         cars_per_cap        country  drives_right
ctrcode
US                809  United States          True
AUS               731      Australia         False
JPN               588          Japan         False
RUS               200         Russia          True
MOR                70        Morocco          True
EG                 45          Egypt          True
IN                 18          India         False

#### Pandas DF from a file

In [226]:
# Import pandas package and file import pandas as pd 
imdb = pd.read_csv ('https://raw.githubusercontent.com/scalabretta/GroupProject--IMDB/master/Dataset/IMDB-database-update.csv',
            encoding = 'latin1')
imdb

,movie_ID,movie_title,duration,color,title_year,country,language,content_rating,budget_USD,gross_USD,...,actor_3_facebook?,actor_3_facebook_likes,cast_total_facebook_likes,movie_facebook?,movie_facebook_likes;,facenumber_in_poster,num_voted_users,num_user_for_reviews,imdb_score,imdb_top_250
0,1,Avatar,178,1,2009,USA,English,PG-13,237000000,760505847,...,1,855,4834,1,33000,0,886204,3054,7.9,0
1,2,Pirates of the Caribbean: At World's End,169,1,2007,USA,English,PG-13,300000000,309404152,...,1,1000,48350,0,0,0,471220,1238,7.1,0
2,3,The Dark Knight Rises,164,1,2012,USA,English,PG-13,250000000,448130642,...,1,23000,106759,1,164000,0,1144337,2701,8.5,1
3,4,Spider-Man 3,156,1,2007,USA,English,PG-13,258000000,336530303,...,1,4000,46055,0,0,0,383056,1902,6.2,0
4,5,Batman v Superman: Dawn of Justice,183,1,2016,USA,English,PG-13,250000000,330249062,...,1,2000,24450,1,197000,0,371639,3018,6.9,0
5,6,Superman Returns,169,1,2006,USA,English,PG-13,209000000,200069408,...,1,903,29991,0,0,0,240396,2367,6.1,0
6,7,Man of Steel,143,1,2013,USA,English,PG-13,225000000,291021565,...,1,748,20495,1,118000,0,548573,2536,7.2,0
7,8,The Hobbit: The Battle of the Five Armies,164,1,2014,New Zealand,English,PG-13,250000000,255108370,...,1,773,9152,1,65000,0,354228,802,7.5,0
8,9,The Amazing Spider-Man,153,1,2012,USA,English,PG-13,230000000,262030663,...,1,963,28489,1,56000,0,451803,1225,7.0,0
9,10,Robin Hood,156,1,2010,USA,English,PG-13,200000000,105219735,...,1,738,3244,1,17000,0,211765,546,6.7,0
10,11,King Kong,201,1,2005,New Zealand,English,PG-13,207000000,218051260,...,1,84,7123,0,0,0,316018,2618,7.2,0
11,12,Titanic,194,1,1997,USA,English,PG-13,200000000,658672302,...,1,794,45223,1,26000,0,793059,2528,7.7,0
12,13,Captain America: Civil War,147,1,2016,USA,English,PG-13,250000000,407197282,...,1,11000,64798,1,72000,0,272670,1022,8.2,1
13,14,Battleship,131,1,2012,USA,English,PG-13,209000000,65173160,...,1,627,26679,1,44000,0,202382,751,5.9,0
14,15,Jurassic World,124,1,2015,USA,English,PG-13,150000000,652177271,...,1,1000,8458,1,150000,0,418214,1290,7.0,0
15,16,Skyfall,143,1,2012,UK,English,PG-13,200000000,304360277,...,1,393,2039,1,80000,0,522030,1498,7.8,0
16,17,Alice in Wonderland,108,1,2010,USA,English,PG,200000000,334185206,...,1,11000,79957,1,24000,0,306320,736,6.5,0
17,18,X-Men: The Last Stand,104,1,2006,Canada,English,PG-13,210000000,234360014,...,1,560,21714,0,0,0,383427,1912,6.8,0
18,19,Monsters University,104,1,2013,USA,English,G,200000000,268488329,...,1,760,14863,1,44000,0,235025,265,7.3,0
19,20,Transformers: Revenge of the Fallen,150,1,2009,USA,English,PG-13,200000000,402076689,...,1,464,3218,0,0,0,323207,1439,6.0,0
20,21,The Amazing Spider-Man 2,142,1,2014,USA,English,PG-13,200000000,202853933,...,1,825,28631,1,41000,0,321227,1067,6.7,0
21,22,TRON: Legacy,125,1,2010,USA,English,PG,170000000,172051787,...,1,1000,25550,1,30000,0,264183,665,6.8,0
22,23,Cars 2,106,1,2011,USA,English,G,200000000,191450875,...,1,776,4482,1,10000,0,101178,283,6.3,0
23,24,Terminator Salvation,118,1,2009,USA,English,PG-13,200000000,125320003,...,1,988,27468,0,0,0,286095,974,6.6,0
24,25,Furious 7,140,1,2015,USA,English,PG-13,190000000,350034110,...,1,14000,79150,1,94000,0,278232,657,7.2,0
25,26,World War Z,123,1,2013,USA,English,PG-13,190000000,202351611,...,1,1000,32392,1,129000,0,465019,995,7.0,0
26,27,Star Trek Into Darkness,132,1,2013,USA,English,PG-13,190000000,228756232,...,1,928,21411,1,92000,0,395573,1171,7.8,0
27,28,Pacific Rim,131,1,2013,USA,English,PG-13,190000000,101785482,...,1,919,19166,1,83000,0,381148,1106,7.0,0
28,29,Brave,93,1,2012,USA,English,PG,185000000,237282182,...,1,838,5005,1,39000,0,273556,428,7.2,0
29,30,WALL-E,98,1,2008,USA,English,G,180000000,223806889,...,1,522,2975,1,16000,0,718837,1043,8.4,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3751,3752,Soul Plane,92,1,2004,USA,English,R,16000000,13922211,...,1,618,3935,0,0,9,18271,150,4.4,0
3752,3753,This Christmas,117,1,2007,USA,English,PG-13,13000000,49121934,...,1,912,6554,0,0,9,6528,32,6.1,0
3753,3754,5 Days of War,113,1,2011,Georgia,English,R,20000000,17149,...,1,18,708,0,0,9,12128,61,5.6,0
3754,3755,Sleepover,89,1,2004,USA,English,PG,10000000,8070311,...,1,2000,13626,0,0,9,12706,75,5.3,0
3755,3756,Baggage Claim,96,1,2013,USA,English,PG-13,8500000,21564616,...,1,1000,8097,0,0,9,7098,41,5.0,0
3756,3757,Best in Show,90,1,2000,USA,English,PG-13,6000000,18621249,...,1,658,4611,0,0,9,45859,340,7.5,0
3757,3758,The Players Club,104,1,1998,USA,English,R,4500000,23031390,...,1,498,2868,1,575,9,4345,26,5.6,0
3758,3759,Little Fockers,98,1,2010,USA,English,PG-13,100000000,148383780,...,1,708,24082,0,0,10,85531,152,5.5,0
3759,3760,Delivery Man,105,1,2013,USA,English,PG-13,26000000,30659817,...,1,110,1006,0,0,10,59805,95,6.4,0
3760,3761,My Big Fat Greek Wedding 2,94,1,2016,USA,English,PG-13,18000000,59573085,...,1,261,2259,1,19000,10,13562,103,6.1,0
3761,3762,Top Five,102,1,2014,USA,English,R,12000000,25277561,...,1,555,5592,0,0,10,21672,93,6.5,0
3762,3763,Movie 43,94,1,2013,USA,English,R,6000000,8828771,...,1,3000,41059,1,25000,10,79146,352,4.3,0
3763,3764,Get on the Bus,120,1,1996,USA,English,R,2400000,5731103,...,1,702,5963,1,352,10,4100,35,6.8,0
3764,3765,The Longest Yard,113,1,2005,USA,English,PG-13,82000000,158115031,...,1,421,13693,0,0,11,130070,316,6.4,0
3765,3766,I Heart Huckabees,107,1,2004,USA,English,R,22000000,12784713,...,1,678,8094,0,0,11,56813,381,6.7,0
3766,3767,Epic Movie,93,1,2007,USA,English,PG-13,20000000,39737645,...,1,729,4293,0,0,11,89687,666,2.3,0
3767,3768,One Direction: This Is Us,106,1,2013,USA,English,PG,10000000,28873374,...,1,547,2787,0,0,11,22161,68,4.1,0
3768,3769,God's Not Dead 2,120,1,2016,USA,English,PG,5000000,20773070,...,1,295,1810,0,0,11,4501,102,3.4,0
3769,3770,Valentine's Day,125,1,2010,USA,English,PG-13,52000000,110476776,...,1,11000,45696,1,9000,12,95437,211,5.7,0
3770,3771,What to Expect When You're Expecting,110,1,2012,USA,English,PG-13,40000000,41102171,...,1,651,13396,1,14000,12,57266,89,5.7,0
3771,3772,Taking Woodstock,120,1,2009,USA,English,R,30000000,7443007,...,1,210,1500,0,0,12,24663,71,6.7,0
3772,3773,Love the Coopers,107,1,2015,USA,English,PG-13,17000000,26284475,...,1,85,10691,0,0,13,9051,68,5.7,0
3773,3774,A Bridge Too Far,175,0,1977,USA,English,PG,26000000,50800000,...,1,14,669,0,0,14,40277,210,7.4,0
3774,3775,The Expendables 3,131,1,2014,USA,English,PG-13,90000000,39292022,...,1,11000,52610,1,56000,15,127258,351,6.1,0
3775,3776,Cheaper by the Dozen,94,1,2003,USA,English,PG,40000000,138614544,...,1,597,7014,0,0,15,75152,288,5.8,0
3776,3777,New Year's Eve,113,1,2011,USA,English,PG-13,56000000,54540525,...,1,307,23456,1,20000,15,66579,134,5.7,0
3777,3778,Boogie Nights,155,1,1997,USA,English,R,15000000,26384919,...,1,170,3677,0,0,15,189032,560,7.9,0
3778,3779,Battle of the Year,110,1,2013,USA,English,PG-13,20000000,8888355,...,1,826,3177,0,0,19,7894,25,5.0,0
3779,3780,The Master,144,1,2012,USA,English,R,32000000,16377274,...,1,15,427,1,27000,31,105144,405,7.1,0
3780,3781,500 Days of Summer,95,1,2009,USA,English,PG-13,7500000,32391374,...,1,11000,54075,1,40000,43,376600,494,7.7,0

In [232]:
# Data Quick Look
imdb[["movie_facebook?"]] = imdb[["movie_facebook?"]].astype('str')
imdb[["movie_facebook?"]]

     movie_facebook?
0                  1
1                  0
2                  1
3                  0
4                  1
5                  0
6                  1
7                  1
8                  1
9                  1
10                 0
11                 1
12                 1
13                 1
14                 1
15                 1
16                 1
17                 0
18                 1
19                 0
20                 1
21                 1
22                 1
23                 0
24                 1
25                 1
26                 1
27                 1
28                 1
29                 1
...              ...
3751               0
3752               0
3753               0
3754               0
3755               0
3756               0
3757               1
3758               0
3759               0
3760               1
3761               0
3762               1
3763               1
3764               0
3765               0
3766               0
3767               0
3768               0
3769               1
3770               1
3771               0
3772               0
3773               0
3774               1
3775               0
3776               1
3777               0
3778               0
3779               1
3780               1

[3781 rows x 1 columns]

In [234]:
imdb.describe()

,movie_ID,duration,color,title_year,budget_USD,gross_USD,net_USD,profitable,director_facebook?,director_facebook_likes,...,actor_top20?.2,actor_3_facebook?,actor_3_facebook_likes,cast_total_facebook_likes,movie_facebook_likes;,facenumber_in_poster,num_voted_users,num_user_for_reviews,imdb_score,imdb_top_250
count,3781.000000,3781.000000,3781.000000,3781.000000,3.781000e+03,3.781000e+03,3.781000e+03,3781.000000,3781.000000,3781.000000,...,3781.000000,3781.000000,3781.000000,3781.000000,3781.000000,3781.000000,3.781000e+03,3781.000000,3781.000000,3781.000000
mean,1891.000000,109.950278,0.967204,2003.081989,4.572770e+07,5.182002e+07,6.092318e+06,0.531870,0.828352,801.610685,...,0.005290,0.992066,764.333774,11417.335625,9264.147051,1.378736,1.039808e+05,331.862470,6.457339,0.041523
std,1091.625012,22.299267,0.178125,9.837954,2.252895e+08,7.003776e+07,2.291199e+08,0.499049,0.377124,3058.757162,...,0.072547,0.088733,1885.768343,19071.218619,21398.159089,2.044844,1.513586e+05,410.112422,1.056270,0.199524
min,1.000000,37.000000,0.000000,1927.000000,2.180000e+02,1.620000e+02,-1.221330e+10,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.200000e+01,1.000000,1.600000,0.000000
25%,946.000000,95.000000,1.000000,1999.000000,1.000000e+07,7.605668e+06,-1.043974e+07,0.000000,1.000000,10.000000,...,0.000000,1.000000,191.000000,1889.000000,0.000000,0.000000,1.831000e+04,105.000000,5.900000,0.000000
50%,1891.000000,106.000000,1.000000,2005.000000,2.500000e+07,2.896520e+07,1.161099e+06,1.000000,1.000000,61.000000,...,0.000000,1.000000,433.000000,3969.000000,217.000000,1.000000,5.250900e+04,207.000000,6.600000,0.000000
75%,2836.000000,120.000000,1.000000,2010.000000,5.000000e+07,6.600997e+07,2.507490e+07,1.000000,1.000000,234.000000,...,0.000000,1.000000,690.000000,16179.000000,11000.000000,2.000000,1.263570e+05,394.000000,7.200000,0.000000
max,3781.000000,325.000000,1.000000,2016.000000,1.221550e+10,7.605058e+08,5.235058e+08,1.000000,1.000000,23000.000000,...,1.000000,1.000000,23000.000000,656730.000000,349000.000000,43.000000,1.689764e+06,5060.000000,9.300000,1.000000

#### Handling Missing & Duplicate Data

In [236]:
imdb.isnull().sum()

movie_ID                     0
movie_title                  0
duration                     0
color                        0
title_year                   0
country                      0
language                     0
content_rating               0
budget_USD                   0
gross_USD                    0
net_USD                      0
profitable                   0
director_name                0
director_top20?              0
director_facebook?           0
director_facebook_likes      0
actor_1_name                 0
actor_top20?                 0
actor_1_facebook?            0
actor_1_facebook_likes       0
actor_2_name                 0
actor_top20?.1               0
actor_2_facebook?            0
actor_2_facebook_likes       0
actor_3_name                 0
actor_top20?.2               0
actor_3_facebook?            0
actor_3_facebook_likes       0
cast_total_facebook_likes    0
movie_facebook?              0
movie_facebook_likes;        0
facenumber_in_poster         0
num_voted_users              0
num_user_for_reviews         0
imdb_score                   0
imdb_top_250                 0
dtype: int64

In [242]:
imdb = imdb.drop_duplicates()
imdb

,movie_ID,movie_title,duration,color,title_year,country,language,content_rating,budget_USD,gross_USD,...,actor_3_facebook?,actor_3_facebook_likes,cast_total_facebook_likes,movie_facebook?,movie_facebook_likes;,facenumber_in_poster,num_voted_users,num_user_for_reviews,imdb_score,imdb_top_250
0,1,Avatar,178,1,2009,USA,English,PG-13,237000000,760505847,...,1,855,4834,1,33000,0,886204,3054,7.9,0
1,2,Pirates of the Caribbean: At World's End,169,1,2007,USA,English,PG-13,300000000,309404152,...,1,1000,48350,0,0,0,471220,1238,7.1,0
2,3,The Dark Knight Rises,164,1,2012,USA,English,PG-13,250000000,448130642,...,1,23000,106759,1,164000,0,1144337,2701,8.5,1
3,4,Spider-Man 3,156,1,2007,USA,English,PG-13,258000000,336530303,...,1,4000,46055,0,0,0,383056,1902,6.2,0
4,5,Batman v Superman: Dawn of Justice,183,1,2016,USA,English,PG-13,250000000,330249062,...,1,2000,24450,1,197000,0,371639,3018,6.9,0
5,6,Superman Returns,169,1,2006,USA,English,PG-13,209000000,200069408,...,1,903,29991,0,0,0,240396,2367,6.1,0
6,7,Man of Steel,143,1,2013,USA,English,PG-13,225000000,291021565,...,1,748,20495,1,118000,0,548573,2536,7.2,0
7,8,The Hobbit: The Battle of the Five Armies,164,1,2014,New Zealand,English,PG-13,250000000,255108370,...,1,773,9152,1,65000,0,354228,802,7.5,0
8,9,The Amazing Spider-Man,153,1,2012,USA,English,PG-13,230000000,262030663,...,1,963,28489,1,56000,0,451803,1225,7.0,0
9,10,Robin Hood,156,1,2010,USA,English,PG-13,200000000,105219735,...,1,738,3244,1,17000,0,211765,546,6.7,0
10,11,King Kong,201,1,2005,New Zealand,English,PG-13,207000000,218051260,...,1,84,7123,0,0,0,316018,2618,7.2,0
11,12,Titanic,194,1,1997,USA,English,PG-13,200000000,658672302,...,1,794,45223,1,26000,0,793059,2528,7.7,0
12,13,Captain America: Civil War,147,1,2016,USA,English,PG-13,250000000,407197282,...,1,11000,64798,1,72000,0,272670,1022,8.2,1
13,14,Battleship,131,1,2012,USA,English,PG-13,209000000,65173160,...,1,627,26679,1,44000,0,202382,751,5.9,0
14,15,Jurassic World,124,1,2015,USA,English,PG-13,150000000,652177271,...,1,1000,8458,1,150000,0,418214,1290,7.0,0
15,16,Skyfall,143,1,2012,UK,English,PG-13,200000000,304360277,...,1,393,2039,1,80000,0,522030,1498,7.8,0
16,17,Alice in Wonderland,108,1,2010,USA,English,PG,200000000,334185206,...,1,11000,79957,1,24000,0,306320,736,6.5,0
17,18,X-Men: The Last Stand,104,1,2006,Canada,English,PG-13,210000000,234360014,...,1,560,21714,0,0,0,383427,1912,6.8,0
18,19,Monsters University,104,1,2013,USA,English,G,200000000,268488329,...,1,760,14863,1,44000,0,235025,265,7.3,0
19,20,Transformers: Revenge of the Fallen,150,1,2009,USA,English,PG-13,200000000,402076689,...,1,464,3218,0,0,0,323207,1439,6.0,0
20,21,The Amazing Spider-Man 2,142,1,2014,USA,English,PG-13,200000000,202853933,...,1,825,28631,1,41000,0,321227,1067,6.7,0
21,22,TRON: Legacy,125,1,2010,USA,English,PG,170000000,172051787,...,1,1000,25550,1,30000,0,264183,665,6.8,0
22,23,Cars 2,106,1,2011,USA,English,G,200000000,191450875,...,1,776,4482,1,10000,0,101178,283,6.3,0
23,24,Terminator Salvation,118,1,2009,USA,English,PG-13,200000000,125320003,...,1,988,27468,0,0,0,286095,974,6.6,0
24,25,Furious 7,140,1,2015,USA,English,PG-13,190000000,350034110,...,1,14000,79150,1,94000,0,278232,657,7.2,0
25,26,World War Z,123,1,2013,USA,English,PG-13,190000000,202351611,...,1,1000,32392,1,129000,0,465019,995,7.0,0
26,27,Star Trek Into Darkness,132,1,2013,USA,English,PG-13,190000000,228756232,...,1,928,21411,1,92000,0,395573,1171,7.8,0
27,28,Pacific Rim,131,1,2013,USA,English,PG-13,190000000,101785482,...,1,919,19166,1,83000,0,381148,1106,7.0,0
28,29,Brave,93,1,2012,USA,English,PG,185000000,237282182,...,1,838,5005,1,39000,0,273556,428,7.2,0
29,30,WALL-E,98,1,2008,USA,English,G,180000000,223806889,...,1,522,2975,1,16000,0,718837,1043,8.4,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3751,3752,Soul Plane,92,1,2004,USA,English,R,16000000,13922211,...,1,618,3935,0,0,9,18271,150,4.4,0
3752,3753,This Christmas,117,1,2007,USA,English,PG-13,13000000,49121934,...,1,912,6554,0,0,9,6528,32,6.1,0
3753,3754,5 Days of War,113,1,2011,Georgia,English,R,20000000,17149,...,1,18,708,0,0,9,12128,61,5.6,0
3754,3755,Sleepover,89,1,2004,USA,English,PG,10000000,8070311,...,1,2000,13626,0,0,9,12706,75,5.3,0
3755,3756,Baggage Claim,96,1,2013,USA,English,PG-13,8500000,21564616,...,1,1000,8097,0,0,9,7098,41,5.0,0
3756,3757,Best in Show,90,1,2000,USA,English,PG-13,6000000,18621249,...,1,658,4611,0,0,9,45859,340,7.5,0
3757,3758,The Players Club,104,1,1998,USA,English,R,4500000,23031390,...,1,498,2868,1,575,9,4345,26,5.6,0
3758,3759,Little Fockers,98,1,2010,USA,English,PG-13,100000000,148383780,...,1,708,24082,0,0,10,85531,152,5.5,0
3759,3760,Delivery Man,105,1,2013,USA,English,PG-13,26000000,30659817,...,1,110,1006,0,0,10,59805,95,6.4,0
3760,3761,My Big Fat Greek Wedding 2,94,1,2016,USA,English,PG-13,18000000,59573085,...,1,261,2259,1,19000,10,13562,103,6.1,0
3761,3762,Top Five,102,1,2014,USA,English,R,12000000,25277561,...,1,555,5592,0,0,10,21672,93,6.5,0
3762,3763,Movie 43,94,1,2013,USA,English,R,6000000,8828771,...,1,3000,41059,1,25000,10,79146,352,4.3,0
3763,3764,Get on the Bus,120,1,1996,USA,English,R,2400000,5731103,...,1,702,5963,1,352,10,4100,35,6.8,0
3764,3765,The Longest Yard,113,1,2005,USA,English,PG-13,82000000,158115031,...,1,421,13693,0,0,11,130070,316,6.4,0
3765,3766,I Heart Huckabees,107,1,2004,USA,English,R,22000000,12784713,...,1,678,8094,0,0,11,56813,381,6.7,0
3766,3767,Epic Movie,93,1,2007,USA,English,PG-13,20000000,39737645,...,1,729,4293,0,0,11,89687,666,2.3,0
3767,3768,One Direction: This Is Us,106,1,2013,USA,English,PG,10000000,28873374,...,1,547,2787,0,0,11,22161,68,4.1,0
3768,3769,God's Not Dead 2,120,1,2016,USA,English,PG,5000000,20773070,...,1,295,1810,0,0,11,4501,102,3.4,0
3769,3770,Valentine's Day,125,1,2010,USA,English,PG-13,52000000,110476776,...,1,11000,45696,1,9000,12,95437,211,5.7,0
3770,3771,What to Expect When You're Expecting,110,1,2012,USA,English,PG-13,40000000,41102171,...,1,651,13396,1,14000,12,57266,89,5.7,0
3771,3772,Taking Woodstock,120,1,2009,USA,English,R,30000000,7443007,...,1,210,1500,0,0,12,24663,71,6.7,0
3772,3773,Love the Coopers,107,1,2015,USA,English,PG-13,17000000,26284475,...,1,85,10691,0,0,13,9051,68,5.7,0
3773,3774,A Bridge Too Far,175,0,1977,USA,English,PG,26000000,50800000,...,1,14,669,0,0,14,40277,210,7.4,0
3774,3775,The Expendables 3,131,1,2014,USA,English,PG-13,90000000,39292022,...,1,11000,52610,1,56000,15,127258,351,6.1,0
3775,3776,Cheaper by the Dozen,94,1,2003,USA,English,PG,40000000,138614544,...,1,597,7014,0,0,15,75152,288,5.8,0
3776,3777,New Year's Eve,113,1,2011,USA,English,PG-13,56000000,54540525,...,1,307,23456,1,20000,15,66579,134,5.7,0
3777,3778,Boogie Nights,155,1,1997,USA,English,R,15000000,26384919,...,1,170,3677,0,0,15,189032,560,7.9,0
3778,3779,Battle of the Year,110,1,2013,USA,English,PG-13,20000000,8888355,...,1,826,3177,0,0,19,7894,25,5.0,0
3779,3780,The Master,144,1,2012,USA,English,R,32000000,16377274,...,1,15,427,1,27000,31,105144,405,7.1,0
3780,3781,500 Days of Summer,95,1,2009,USA,English,PG-13,7500000,32391374,...,1,11000,54075,1,40000,43,376600,494,7.7,0

#### Get started with your Data

In [245]:
#Example for duration and gross_USD 
imdb[["duration", "gross_USD"]].describe()

          duration     gross_USD
count  3781.000000  3.781000e+03
mean    109.950278  5.182002e+07
std      22.299267  7.003776e+07
min      37.000000  1.620000e+02
25%      95.000000  7.605668e+06
50%     106.000000  2.896520e+07
75%     120.000000  6.600997e+07
max     325.000000  7.605058e+08

In [251]:
# Example
imdb["color"].value_counts()

1    3657
0     124
Name: color, dtype: int64

In [250]:
imdb["content_rating"].value_counts()

R            1715
PG-13        1311
PG            568
G              88
Not Rated      39
Unrated        24
Approved       14
X              10
NC-17           6
Passed          3
M               2
GP              1
Name: content_rating, dtype: int64

#### High Rating Movies Criteria

In [252]:
data = imdb[budget_USD, duration]

NameError: name 'budget_USD' is not defined

## Individual Assignment

In [254]:
# How many rows and columns reflected on dataset file IMDB-database-update.csv
imdb.shape

(3781, 36)

In [257]:
#  What are the top 3 movies with highest nett profit in 2013? 
imdb.head()

,movie_ID,movie_title,duration,color,title_year,country,language,content_rating,budget_USD,gross_USD,...,actor_3_facebook?,actor_3_facebook_likes,cast_total_facebook_likes,movie_facebook?,movie_facebook_likes;,facenumber_in_poster,num_voted_users,num_user_for_reviews,imdb_score,imdb_top_250
0,1,Avatar,178,1,2009,USA,English,PG-13,237000000,760505847,...,1,855,4834,1,33000,0,886204,3054,7.9,0
1,2,Pirates of the Caribbean: At World's End,169,1,2007,USA,English,PG-13,300000000,309404152,...,1,1000,48350,0,0,0,471220,1238,7.1,0
2,3,The Dark Knight Rises,164,1,2012,USA,English,PG-13,250000000,448130642,...,1,23000,106759,1,164000,0,1144337,2701,8.5,1
3,4,Spider-Man 3,156,1,2007,USA,English,PG-13,258000000,336530303,...,1,4000,46055,0,0,0,383056,1902,6.2,0
4,5,Batman v Superman: Dawn of Justice,183,1,2016,USA,English,PG-13,250000000,330249062,...,1,2000,24450,1,197000,0,371639,3018,6.9,0

In [ ]:
imdb_2013 = [(imdb.country == "Australia")]